# Generated by Django 3.0.5 on 2020-05-03 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('number_of_paychecks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_paid', models.DateField(null=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Frequency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CheckInPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Frequency')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Income')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('projected_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('futures_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outgoing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_modified', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('last_paid', models.DateField(null=True)),
                ('weekdays_only', models.BooleanField(default=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Frequency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.AccountType'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client'),
        ),
    ]
