# Generated by Django 2.2.6 on 2019-10-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20191006_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total',
            new_name='amount',
        ),
    ]
