# Generated by Django 2.2.6 on 2019-10-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20191010_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpreferences',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Account'),
            preserve_default=False,
        ),
    ]
