# Generated by Django 2.2.6 on 2019-10-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_checkinpreferences_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinpreferences',
            name='income',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='budget.Income'),
            preserve_default=False,
        ),
    ]
