# Generated by Django 2.2.6 on 2019-10-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_checkinpreferences_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='actual_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
